while (false) {
    fun foo() { continue; } // Error at 'continue': Can't continue outside loop.
}
